### ISSUE TITLE
Exception raised to user when running game.

### ISSUE THREAD

**Issue by pji** [pji/blackjack#1]
Received the following when running backjack.cli -2:

```

Another round? > y

Player          Action          Hand
──────────────────────────────────────────────────
John            Initial bet.    2 (198)
Michael         Initial bet.    2 (150)
John            Initial deal.   A♣ Q♠
Michael         Initial deal.   Q♣ Q♦
Dealer          Initial deal.   4♥ ──
John            Stand.          21
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/pji/Dev/blackjack/blackjack/cli.py", line 176, in <module>
    two_player()
  File "/Users/pji/Dev/blackjack/blackjack/cli.py", line 155, in two_player
    g.play()
  File "/Users/pji/Dev/blackjack/blackjack/game.py", line 145, in play
    if self._split(player.hands[0], player):
  File "/Users/pji/Dev/blackjack/blackjack/game.py", line 270, in _split
    if hand[0].rank == hand[1].rank and player.will_split(hand):
  File "/Users/pji/Dev/blackjack/blackjack/players.py", line 108, in will_split_recommended
    dhand = the_game.dealer.hands[0]
AttributeError: 'NoneType' object has no attribute 'dealer'

```

**Comment by pji** [comment]
Issue is that Game._split() isn't sending the Game object to Player.will_split(). Shouldn't be any side effects to the fix. Probably just need to make the the_game parameter of will_split() required, so that the unit tests catch any issues.

**Comment by pji** [comment]
Fix confirmed.
